# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venCalendar(object):
    def setupUi(self, venCalendar):
        venCalendar.setObjectName("venCalendar")
        venCalendar.resize(400, 300)
        self.Calendar = QtWidgets.QCalendarWidget(venCalendar)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.Calendar.setObjectName("Calendar")

        self.retranslateUi(venCalendar)
        QtCore.QMetaObject.connectSlotsByName(venCalendar)

    def retranslateUi(self, venCalendar):
        _translate = QtCore.QCoreApplication.translate
        venCalendar.setWindowTitle(_translate("venCalendar", "Dialog"))
