# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.setWindowModality(QtCore.Qt.WindowModal)
        windowaviso.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(windowaviso)
        self.buttonBox.setGeometry(QtCore.QRect(100, 220, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(windowaviso)
        self.label.setGeometry(QtCore.QRect(130, 30, 128, 128))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/warning/warning.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(windowaviso)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(windowaviso)
        self.buttonBox.accepted.connect(windowaviso.accept) # type: ignore
        self.buttonBox.rejected.connect(windowaviso.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Aviso"))
        self.label_2.setText(_translate("windowaviso", "¿Desea Salir?"))
import warning_rc
